name: slog_core
description: The core logger for SLogs.
version: 0.1.0+1
repository: https://github.com/SeanfvdM/slog/tree/main/packages/slog_core

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  meta: ^1.8.0
  stack_trace: ^1.10.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
