name: slog_core
description: A Basic Logger and Core for SLogs. A logger that wants to be more flexible.
version: 0.2.0
repository: https://github.com/SeanfvdM/slog/tree/main/packages/slog_core

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  async: ^2.10.0
  meta: ^1.8.0
  stack_trace: ^1.10.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
